# render.yaml
services:
  - type: web
    name: propwire-scraper-clean
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18
